language: groovy

before_script:
 - chmod +x grailsw

script:
 - ./grailsw refresh-dependencies
 - ./grailsw war

deploy:
  provider: openshift
  user: denis.shybeko@gmail.com
  password: CHuVNCjc
  domain: bboards
  app: badmin
